version: "3.3"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - blachere_volume:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped
volumes: 
  blachere_volume: